# Example configuration file for Dual Carousel Slideshow
# Copy this file to config.yaml and modify as needed

display:
  monitor_index: 1              # 0=primary, 1=secondary, etc.
  always_on_top: true           # Keep window always on top
  hide_cursor_after_ms: 2000    # Hide cursor after 2 seconds of inactivity
  background_color: "#000000"   # Background color (hex format)
  use_true_fullscreen: false    # Use pygame.FULLSCREEN (may minimize on focus loss)

schedule:
  mode: "fixed"                 # "fixed" or "sun"
  
  # Fixed schedule configuration
  fixed_schedule:
    day_start: "06:00"          # Time to switch to day mode (24h format)
    night_start: "18:00"        # Time to switch to night mode (24h format)
  
  # Sun-based schedule configuration
  sun_schedule:
    latitude: 40.7128           # Your location latitude
    longitude: -74.0060         # Your location longitude (NYC example)
    day_offset_minutes: 0       # Minutes to offset sunrise (+ = later, - = earlier)
    night_offset_minutes: 0     # Minutes to offset sunset (+ = later, - = earlier)

playback:
  interval_seconds: 5           # Seconds between image changes
  shuffle: true                 # Randomize image order
  fit_mode: "cover"             # "cover" (fill screen) or "fit" (fit with bars)
  transition_ms: 300            # Crossfade transition duration in milliseconds
  reload_images_every_seconds: 300  # Rescan folders every 5 minutes
  resume_index_between_runs: true   # Remember last image position

folders:
  day: "./images/day"           # Path to day images folder
  night: "./images/night"       # Path to night images folder
  include_subfolders: true      # Include images from subfolders

logging:
  level: "INFO"                 # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_to_file: true             # Enable file logging
  log_file_path: "./logs/slideshow.log"  # Log file path
  max_file_size_mb: 10          # Max log file size before rotation
  backup_count: 5               # Number of backup log files to keep
  log_to_console: true          # Also log to console